### PR TITLE
Fixing zip file format

### PR DESCRIPTION
**Pull request by angeloc**
This patch fixes various errors with git archive zip file format.

### CODE REVIEW

**Comment by urjaman** [comment]
I guess atleast this one when trying a second time to make a zip from a repo...

git-archive-all: line 221: $TMPDIR/$(basename "$(pwd)").$FORMAT: cannot overwrite existing file

**Comment by meitar** [comment]
Oh, I see. When trying a *second* time. Right, that's because the file already exists. I'm not sure silently overwriting the file is a good idea here, since the output of this script is *not* identical to `git-archive`. Can someone make a compelling argument why overwriting a previously-created archive, instead of just erroring and letting the user move it aside or `rm` it themselves, is a good idea?

**Comment by urjaman** [comment]
But it's not the final output... actually i tried this thing on cygwin (just saying if it is relevant...) and specified output as ~/name.zip and it seemed to do stuff but no ~/name.zip was created. I tried it again without the ~ (with /home/username/name.zip ) and then got this error. At this point I gave up and used a different method.

**Comment by meitar** [comment]
> But it's not the final output (its an archive output in /tmp/ ...)

Oh! My bad. :) Yeah in that case it makes more sense.

**Comment by flying-sheep** [comment]
bumpy bump

**Pull request merged**
